# -*- coding: utf-8 -*-
#
# eml-parser documentation build configuration file, created by
# sphinx-quickstart on Tue Mar  7 23:53:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import pathlib
sys.path.insert(0, os.path.abspath('..'))

setuppy_version = 'Unknown'
setuppy_author = 'Unknown'
setuppy_name = 'Unknown'

setuppy_path = pathlib.Path(os.path.abspath('..'), 'setup.py')

if setuppy_path.is_file():
  with open(str(setuppy_path), 'r') as fhdl:
    for line in fhdl.readlines():
      if 'version=' in line:
        setuppy_version = line.split('=', 1)[1].replace('\'', '').replace(',', '').strip()

      if 'author=' in line:
        setuppy_author = line.split('=', 1)[1].replace('\'', '').replace(',', '').strip()

      if 'name=' in line:
        setuppy_name = line.split('=', 1)[1].replace('\'', '').replace(',', '').strip()


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.napoleon',
              'sphinx.ext.coverage',
              'sphinx.ext.githubpages',
              ]

autoclass_content = 'both'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = setuppy_name
copyright = '2014-present, Georges Toth'
author = setuppy_author

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = setuppy_version
# The full version, including alpha/beta/rc tags.
release = setuppy_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
